//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruyenTranh_ManagermentPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chuong
    {
        public int idChuong { get; set; }
        public string tenChuong { get; set; }
        public int idComic { get; set; }
        public string content { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Comic Comic { get; set; }
    }
}
