//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruyenTranh_ManagermentPage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Managerment_PageEntities : DbContext
    {
        public Managerment_PageEntities()
            : base("name=Managerment_PageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Account_Detail> Account_Detail { get; set; }
        public virtual DbSet<Chuong> Chuongs { get; set; }
        public virtual DbSet<Comic> Comics { get; set; }
        public virtual DbSet<Forgot_Password> Forgot_Password { get; set; }
        public virtual DbSet<ListFavourite> ListFavourites { get; set; }
        public virtual DbSet<Type_Comic> Type_Comic { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Detail> User_Detail { get; set; }
    }
}
