//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruyenTranh_ManagermentPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Detail
    {
        public int idAccount { get; set; }
        public string fullname { get; set; }
        public System.DateTime DOB { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<bool> status { get; set; }
        public string imgAccount { get; set; }
    
        public virtual User User { get; set; }
    }
}
